name: Rohit Awate
description: Computer science, cinema, technology and business.
meta_description: "Rohit Awate: Computer science, cinema, technology and business."
date: 2021
permalink: /:title

markdown: kramdown
highlighter: rouge

logo: false
paginate: 15
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "/"
domain_name: awate.in
author: "Rohit"
