name: Rohit Awate
description: Computers, films, dogs and mountains
meta_description: Rohit Awate. Computers, films, dogs and mountains
date: 2021
permalink: /:year/:month/:day/:title

markdown: kramdown
highlighter: rouge

logo: false
paginate: 15
google_analytics: ""
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "/"
author: "Rohit"
